### ISSUE TITLE
Remove hard-coded text beneath logo in site header

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-wcij#10]
Remove the "Produced by the Wisconsin Center for Investigative Journalism" text from beneath the logo in the site header.

**Comment by benlk** [comment]
Do they also want to remove the "Protect the vulnerable / expose wrongdoing / explore solutions" text at the top? https://www.wisconsinwatch.org/ 


![Screen Shot 2019-06-05 at 16 03 53 ](https://user-images.githubusercontent.com/1754187/58986506-89a59b80-87ab-11e9-8758-94ac8821cdd4.png)

**Comment by MirandaEcho** [comment]
Just the "Produced by the Wisconsin Center for Investigative Journalism" text at this point.  Thanks!
