### ISSUE TITLE
Update subscription button and form 

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-wcij#15]
"Would it be possible to replace the custom coded form on our homepage with a prominent "Subscribe" button that would take people to wisconsinwatch.org/subscribe? Then would you be able to update the gravity form on that page to include this option: "Wisconsin COVID-19 Update - A roundup of top news and information about Wisconsin's response to the coronavirus." And would it be possible for you to update it in a way that allows us to make those changes in the future?"

- [ ]  replace that form with a button
- [ ] update the gravity form for them, which they can then update themselves in the future

**Comment by benlk** [comment]
To edit the form, edit form with ID 3: https://staging.wisconsinwatch.flywheelsites.com/wp-admin/admin.php?page=gf_edit_forms&id=3

The text above the form on this page is just part of the post content; https://staging.wisconsinwatch.flywheelsites.com/wp-admin/post.php?post=719313&action=edit

https://github.com/INN/umbrella-wcij/pull/16 contains the necessary code changes.

**Comment by MirandaEcho** [comment]
Requested changes: 

- For wisconsinwatch.org/subscribe:
We made a few changes, based on the instructions you sent, to that page in staging. Is it possible to push those changes live?

- For the homepage:
We played around with the header and the button in the newsletter widget. I'm attaching to this email an image Coburn mocked up in photoshop. We're wondering if it's possible to make a few style changes so the widget appears as it does in the mockup. First, could we remove the date and Madison, Wisconsin from the homepage, because we found that it looks slightly odd now above the button. Second, we noticed that if the button's text is only one line long, the button itself doesn't center inside the gray box. Is it possible to have that button centered? Third, is it possible to move the widget down so it's level with our logo above the thicker gray line?

I'll attach an image that illustrates how the button doesn't center and how the widget hovers above the thicker gray line. Hopefully this all makes sense, and please let me know if it doesn't!

Mockup of how they want it to look: 
![image](https://user-images.githubusercontent.com/48263361/78798234-58bf6580-797e-11ea-9015-12b39e0a1114.png)

**Comment by benlk** [comment]
- [ ] copy page content changes for `/subscribe/` from staging to live, when they're ready
- [x] remove date
- [x] remove location
- [x] center text
- [x] align sole widget in that widget area with bottom of page

**Comment by benlk** [comment]
@MirandaEcho Staging is ready for them to take another look. Two questions:

1. Should we copy the subscription page content changes over now, or wait until everything else is deployed?
2. Does the rest of this look ready?

**Comment by MirandaEcho** [comment]
Thanks @benlk! They've been quick to respond, so its probably more efficient to do it all at once. 

Email sent!  I'll let you know when I hear back.

**Comment by benlk** [comment]
:deployed: and configured
