### ISSUE TITLE
Trust Project buttons

### ISSUE THREAD

**Issue by tylermachado** [INN/umbrella-wcij#4]
Option 2: shortcodes added to the custom sidebar plus styling - 2-4 hours

![image](https://user-images.githubusercontent.com/3586466/46153526-4fa9f000-c241-11e8-937e-446f875a07d4.png)

RESULT:
- [ ] replace usual header with Trust Project logo
- [ ] first button should link to sitewide policies
- [ ] second button should link to "Behind the Story"

**Comment by benlk** [comment]
These styles may need to be updated after the changes made in https://github.com/INN/trust-indicators/pull/94/
